/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
static yyconst short int yy_accept[361] =
    {   0,
        1,    1,   30,   29,    1,   28,   29,   29,   12,   13,
       29,    7,    7,   13,   13,   12,    9,   12,    8,   10,
       29,   29,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,    1,    0,
        0,   16,    0,   15,    9,   10,    9,    0,    2,   13,
       27,    0,   27,   27,   27,    0,   27,   27,   27,   27,
       27,   27,   27,   27,    5,   27,   27,   27,   27,   27,
       27,    5,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   11,    0,   16,
       16,   16,    0,    0,    0,    0,   15,   15,   15,    0,

        0,    2,    0,   19,    0,    0,   14,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
        6,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,    0,    0,    0,    0,    0,    2,
       17,   27,   27,   27,   27,   27,   27,   27,    0,   27,
       27,   27,   27,   27,   27,   27,    8,   27,   27,   27,
       27,    0,    0,    0,   17,   17,   17,   27,   27,   27,
       27,    0,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,    0,    0,    0,    0,   27,    0,    0,    0,
        0,   27,   27,   27,   27,    0,   27,    0,   26,    0,

        0,    0,   21,    0,    0,   18,    0,   27,   27,    0,
        0,    0,   21,   21,   21,    0,    0,    0,    0,    0,
        0,    0,    0,   20,   27,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,   20,
       20,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   23,    0,   24,    0,    0,    0,

        0,    0,    0,   23,   23,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   25,    0,    0,    0,   25,    0,   25,   25,    0,
        4,    0,    0,    0,    0,    0,   22,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   25,   25,   25,   25,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,    2,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,    1,   28,    9,    8,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   38,   45,   46,   47,   48,   49,   50,   38,
       51,   38,   52,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    5,    1,    1,
        6,    7,    1,    1,    8,    5,    5,    5,    9,    9,
        9,    1,    1,    1,   10,   11,   12,    1,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    1
    } ;

static yyconst short int yy_base[396] =
    {   0,
        0,    0,  942, 1014,   51, 1014,    0,  903, 1014, 1014,
        0,    0, 1014,    0,   37,   42,   45,   54,   54,   59,
      905,  900,   73,   93,   79,   52,   83,   89,   97,   53,
      100,  101,  108,  105,  114,   60,  117,  120,   66,  917,
      879,  150,  168,  174,   67,  158,  177,  905,    0, 1014,
       92,  904,  156,  157,  160,  887,  161,  174,  165,  180,
      170,  185,  173,  184,  188,  189,  194,  198,  177,  197,
      207,  202,  206,  211,  212,  221,  216,  220,  225,  232,
      231,  235,  236,  247,  228,  248,  251, 1014,  880,  281,
        0,    0,  281,  303,    0,    0,  309,    0,    0,  895,

      290,    0,  894,  893,    0,  876,  864,  269,  289,  298,
      270,  290,  295,  304,  309,  312,  308,  313,  317,  328,
      340,  321,  325,  332,  333,  343,  322,  349,  354,  353,
      358,  359,  373,  339,  840,  844,  103,  829,  385,  838,
      403,  369,  382,  370,  386,  397,  389,  396,    0,  404,
      400,  401,  408,  417,  421,  414,  413,  420,  426,  425,
      434,  802,  845,  455,  464,    0,    0,  474,  453,  454,
      457,  512,  445,  460,  464,  469,  468,  465,  492,  482,
      491,  497,  814,  526,  540,    0,  535,  573,  832,    0,
        0,  508,  540,  519,  522,  801,  528,  809, 1014,  587,

        0,    0,  605,  597,  828,  825,    0,  543,  555,  806,
      830,  811,  643,    0,    0,  786,   81,  784,  786,  773,
      766,  762,  760,  636,  571,  575,  761,   54,  797,  757,
      770,  761,  741,  745,  740,  741,  739,  745,  650,    0,
        0,  758,  743,  740,  155,  728,  731,  725,  723,  738,
      738,  760,  726,  725,  723,  707,  711,  706,  158,  544,
      362,  705,  710,  702,    0,  698,  704,  687,  690,  692,
      273,  705,  722,  692,  664,  689,  681,  678,  717,  684,
      663,  664,  670,    0,  678,  697,    0,    0,  675,  674,
      662,  662,  657,  651,  684,  675,  667,  646,  635,  643,

      627,  642,  634,  698,    0,    0,  646,  620,  644,  609,
      594,  636,  602,  597,  591,  603,    0,  593,  600,  585,
      598,  712,  572,  613,  583,  726,  608,    0,    0,    0,
     1014,  567,  740,  529,  758,    0, 1014,    0,  479,  580,
      553,  554,  557,  567,  549,  535,  523,  532,  523,  516,
      496,  514,  461,    0,  461,  776,  790,    0,    0, 1014,
      811,  424,  384,  339,  819,  827,  836,  843,  854,  866,
      878,  890,  284,  898,  276,  901,  908,  915,  249,  926,
      936,  163,  943,  954,  162,  962,  119,  973,  981,   88,
      988,   72,  995,   58, 1002

    } ;

static yyconst short int yy_def[396] =
    {   0,
      360,    1,  360,  360,  360,  360,  361,  360,  360,  360,
      362,  363,  360,  364,  360,  360,  360,  360,  360,  360,
      360,  360,  365,  365,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,  360,  361,
      360,  366,  367,  368,  360,  360,  360,  369,  370,  360,
       24,  371,   24,   24,   24,  372,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,  360,  360,  366,
       90,   90,  360,  367,   94,   94,  368,   97,   97,  369,

      369,  370,  371,  371,  373,  372,  372,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,  360,  360,  360,  360,  360,  369,
      374,   24,   24,   24,   24,   24,   24,   24,  375,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,  360,  360,  376,  374,  165,  165,   24,   24,   24,
       24,  377,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,  360,  360,  378,  379,   24,  377,  380,  188,
      188,   24,   24,   24,   24,  360,   24,  360,  360,  378,

      200,  200,  381,  360,  380,  380,  382,   24,   24,  360,
      360,  360,  381,  213,  213,  360,  360,  360,  360,  360,
      360,  360,  360,  383,   24,   24,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  383,  239,
      239,  360,  360,  360,  384,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  384,  384,
      360,  360,  360,  360,  385,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  386,  360,  360,  360,  360,  360,
      360,  360,  360,  387,  386,  388,  285,  285,  360,  360,
      360,  360,  360,  360,  389,  388,  388,  360,  360,  360,

      360,  360,  360,  389,  304,  304,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  390,  360,  360,  360,
      360,  391,  360,  360,  360,  391,  360,  326,  326,  392,
      360,  360,  393,  360,  393,  335,  360,  335,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  394,  360,  395,  395,  357,  357,    0,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360

    } ;

static yyconst short int yy_nxt[1067] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,    4,   16,   17,   18,   19,   19,
       20,    4,   21,   10,   22,   23,   13,   13,   23,   24,
       25,   26,   27,   28,   23,   23,   29,   23,   23,   23,
       30,   31,   23,   32,   33,   34,   35,   36,   37,   38,
       23,   13,   39,   45,   39,   46,   46,   46,   45,  245,
       46,   46,   46,   47,   47,   47,   48,   39,  356,   39,
       45,   49,   46,   46,   46,   45,  245,   46,   46,   46,
       51,   74,  333,   52,   64,   47,   47,   47,   53,   51,
       51,   54,   54,   54,   65,   55,   55,   55,  322,   56,

       51,   83,   55,   52,   55,   84,  164,   59,   53,   51,
       51,   54,   54,   54,   60,   61,  231,   68,   62,   56,
      232,   63,   66,   55,   67,   55,  163,   55,   69,  295,
       72,   70,   75,   71,   55,   57,   55,   58,   73,   55,
       78,   55,   55,   55,   55,   76,   81,   55,   77,   55,
       55,   79,   55,   85,   80,   87,   55,   90,   82,   86,
      260,   55,   55,  260,   55,   90,   90,   90,   91,   91,
       91,   93,  275,  224,   45,   94,   46,   46,   46,  260,
      105,   97,  260,   94,   94,   94,   95,   95,   95,   97,
       97,   97,   98,   98,   98,   47,   47,   47,   55,   55,

       55,   55,   55,  108,   55,   55,  109,   55,  111,   55,
      110,   72,   55,  112,   55,   55,   55,   55,   55,  119,
      113,   55,   55,  114,   55,  117,   55,   55,   55,   55,
       55,   55,   55,   55,  116,  115,   55,  118,   55,   55,
       55,   72,   55,  120,   55,  124,   55,  122,   55,   55,
       55,   55,  121,   55,   55,   55,   55,  123,   55,  203,
       55,   72,   55,   55,   55,   55,  125,   55,  127,  126,
       55,  128,  132,   55,   55,   55,   55,   55,   55,   55,
       55,  130,  129,  131,  133,  136,  172,  134,   90,   55,
       55,   55,   55,   55,  141,   55,   90,   90,   90,   91,

       91,   91,  101,  137,  138,  139,   93,  140,  121,  281,
       94,   55,   55,   55,  121,  282,   97,  142,   94,   94,
       94,   95,   95,   95,   97,   97,   97,   98,   98,   98,
       72,   55,   55,   55,   55,  143,  144,   55,  145,   55,
       55,   72,   55,  149,   72,  147,   55,   72,   55,   44,
       55,   55,   55,   55,   55,   55,   55,   55,  146,   55,
      148,   55,   72,   55,   55,   55,   55,   55,  155,   55,
       55,  151,   55,  150,   55,   55,   55,   55,  161,  153,
      152,   55,   55,   55,   55,   55,  157,   55,  164,  158,
      154,   55,  156,   55,   43,   55,   55,   55,   55,  159,

       55,   55,   55,   55,  121,  160,  271,   72,  163,  272,
      165,   55,   55,   55,   55,   55,  169,   55,  165,  165,
      165,  166,  166,  166,   55,  170,   55,  168,   55,  157,
       55,   55,  173,   55,   42,  121,  174,  171,   55,   55,
       55,   55,   55,   55,   55,  175,   55,  177,   55,  176,
       55,  178,   55,  179,  180,   55,   55,   55,   55,   55,
      181,   55,   55,   55,   55,   55,   72,   55,   55,   55,
       55,  165,  182,  184,  184,  184,   55,  186,   55,  165,
      165,  165,  166,  166,  166,   72,  121,   55,  187,   55,
       72,  192,  352,  355,  196,   55,   55,   55,   55,   55,

       72,   55,   55,  121,   55,   72,   55,   55,   55,   55,
       55,   55,   55,   55,  193,  341,   55,  354,   55,  188,
      194,  342,  189,  195,   55,  197,   55,  188,  188,  188,
      190,  190,  190,   55,   55,   55,   55,  199,  204,   55,
       72,   55,  353,  207,  184,  184,  184,  200,  352,  260,
       55,  199,   55,  352,  209,  200,  200,  200,  201,  201,
      201,   55,  351,   55,   55,  208,   55,   72,  260,  350,
       55,  349,   55,  339,  242,  225,  340,   55,  243,   55,
      188,  348,   55,  189,   55,   55,  226,   55,  188,  188,
      188,  190,  190,  190,  200,  347,  346,   55,  199,   55,

      345,  344,  200,  200,  200,  201,  201,  201,  212,  343,
      334,  332,  213,   55,  331,   55,  330,   55,  252,   55,
      213,  213,  213,  214,  214,  214,  216,  217,  218,  312,
      219,  325,  324,  220,  323,  321,  320,  319,  318,  317,
      316,  312,  221,  239,  222,  223,  212,  315,  314,  313,
      213,  239,  239,  239,  240,  240,  240,  239,  213,  213,
      213,  214,  214,  214,  312,  239,  239,  239,  240,  240,
      240,  285,  311,  310,  286,  309,  308,  307,  297,  285,
      285,  285,  287,  287,  287,  285,  297,  303,  286,  302,
      301,  304,  300,  285,  285,  285,  287,  287,  287,  304,

      304,  304,  305,  305,  305,  304,  299,  298,  297,  294,
      293,  292,  291,  304,  304,  304,  305,  305,  305,  326,
      149,  290,  289,  252,  252,  284,  327,  326,  326,  326,
      328,  328,  328,  326,  283,  280,  279,  278,  277,  276,
      327,  326,  326,  326,  328,  328,  328,  335,  252,  274,
      273,  270,  269,  268,  252,  335,  335,  335,  336,  336,
      336,  267,  266,  265,  337,  335,  264,  263,  262,  252,
      252,  261,  258,  335,  335,  335,  336,  336,  336,  257,
      256,  255,  337,  357,  254,  253,  252,  251,  250,  249,
      327,  357,  357,  357,  358,  358,  358,  357,  248,  247,

      246,  244,  238,  237,  327,  357,  357,  357,  358,  358,
      358,   40,  236,   40,  235,   40,   40,   40,   40,   40,
       40,   40,   40,   55,   55,  234,  233,   55,  230,   55,
       55,   92,  229,  228,  227,   92,  206,   92,   96,  206,
       96,  211,  210,  206,   96,  198,   96,   99,  164,  183,
      101,   99,  163,   99,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  102,  163,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  103,  162,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      106,  107,  106,  106,  106,  106,  106,  106,  106,  106,

      106,  106,  167,  107,  104,  104,  167,  101,  167,  185,
      135,  185,  191,  191,  107,  104,  191,  101,  191,  202,
       89,  202,   88,  202,   50,  202,  205,   50,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  215,   41,
      215,  360,  360,  360,  215,  360,  215,  241,  360,  360,
      360,  241,  360,  241,  259,  360,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  288,  288,  360,  360,
      288,  360,  288,  296,  360,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  306,  360,  360,  360,  306,
      360,  306,  329,  360,  360,  329,  329,  360,  329,  338,

      360,  360,  360,  338,  338,  338,  359,  360,  360,  359,
      359,  360,  359,    3,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360
    } ;

static yyconst short int yy_chk[1067] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,   15,    5,   15,   15,   15,   16,  228,
       16,   16,   16,   17,   17,   17,   18,   39,  394,   39,
       19,   18,   19,   19,   19,   20,  228,   20,   20,   20,
       23,   30,  392,   23,   26,   45,   45,   45,   23,   23,
       23,   23,   23,   23,   26,   30,   26,   30,  390,   23,

       24,   36,   36,   24,   36,   36,  137,   25,   24,   24,
       24,   24,   24,   24,   25,   25,  217,   28,   25,   24,
      217,   25,   27,   25,   27,   27,  137,   27,   28,  387,
       29,   28,   31,   28,   51,   24,   51,   24,   29,   29,
       33,   29,   31,   32,   31,   32,   35,   34,   32,   34,
       33,   34,   33,   37,   34,   38,   35,   42,   35,   37,
      245,   37,   38,  259,   38,   42,   42,   42,   42,   42,
       42,   43,  385,  382,   46,   43,   46,   46,   46,  245,
       53,   44,  259,   43,   43,   43,   43,   43,   43,   44,
       44,   44,   44,   44,   44,   47,   47,   47,   53,   54,

       53,   54,   55,   57,   55,   57,   58,   59,   60,   59,
       59,   61,   61,   62,   61,   63,   58,   63,   58,   69,
       63,   69,   60,   64,   60,   67,   64,   62,   64,   62,
       65,   66,   65,   66,   66,   65,   67,   68,   67,   70,
       68,   70,   68,   71,   72,   77,   72,   74,   73,   71,
       73,   71,   73,   74,   75,   74,   75,   76,   77,  379,
       77,   75,   78,   76,   78,   76,   78,   79,   80,   79,
       85,   81,   85,   81,   80,   81,   80,   82,   83,   82,
       83,   83,   82,   84,   86,   93,  375,   87,   90,   84,
       86,   84,   86,   87,  373,   87,   90,   90,   90,   90,

       90,   90,  101,   93,   93,   93,   94,  101,  108,  271,
       94,  108,  111,  108,  111,  271,   97,  109,   94,   94,
       94,   94,   94,   94,   97,   97,   97,   97,   97,   97,
      110,  109,  112,  109,  112,  112,  114,  113,  115,  113,
      110,  113,  110,  121,  116,  119,  114,  117,  114,  364,
      117,  115,  117,  115,  116,  118,  116,  118,  118,  119,
      120,  119,  122,  122,  127,  122,  127,  123,  127,  123,
      120,  124,  120,  123,  124,  125,  124,  125,  134,  126,
      125,  134,  121,  134,  121,  126,  129,  126,  139,  130,
      126,  128,  128,  128,  363,  130,  129,  130,  129,  131,

      131,  132,  131,  132,  133,  132,  261,  142,  139,  261,
      141,  142,  144,  142,  144,  133,  144,  133,  141,  141,
      141,  141,  141,  141,  143,  145,  143,  143,  145,  146,
      145,  147,  150,  147,  362,  147,  151,  148,  148,  146,
      148,  146,  151,  152,  151,  152,  150,  154,  150,  153,
      153,  155,  153,  156,  158,  157,  156,  157,  156,  154,
      159,  154,  158,  155,  158,  155,  161,  160,  159,  160,
      159,  165,  160,  164,  164,  164,  161,  168,  161,  165,
      165,  165,  165,  165,  165,  169,  170,  173,  171,  173,
      174,  173,  355,  353,  181,  169,  170,  169,  170,  171,

      178,  171,  174,  176,  174,  175,  175,  178,  175,  178,
      177,  176,  177,  176,  177,  339,  168,  352,  168,  172,
      179,  339,  172,  180,  180,  182,  180,  172,  172,  172,
      172,  172,  172,  181,  179,  181,  179,  184,  187,  182,
      192,  182,  351,  193,  184,  184,  184,  185,  350,  260,
      192,  185,  192,  349,  195,  185,  185,  185,  185,  185,
      185,  194,  348,  194,  195,  194,  195,  197,  260,  347,
      197,  346,  197,  334,  225,  208,  334,  187,  226,  187,
      188,  345,  193,  188,  193,  208,  209,  208,  188,  188,
      188,  188,  188,  188,  200,  344,  343,  209,  200,  209,

      342,  341,  200,  200,  200,  200,  200,  200,  203,  340,
      332,  327,  203,  225,  325,  225,  324,  226,  323,  226,
      203,  203,  203,  203,  203,  203,  204,  204,  204,  321,
      204,  320,  319,  204,  318,  316,  315,  314,  313,  312,
      311,  310,  204,  224,  204,  204,  213,  309,  308,  307,
      213,  224,  224,  224,  224,  224,  224,  239,  213,  213,
      213,  213,  213,  213,  303,  239,  239,  239,  239,  239,
      239,  275,  302,  301,  275,  300,  299,  298,  297,  275,
      275,  275,  275,  275,  275,  285,  296,  294,  285,  293,
      292,  295,  291,  285,  285,  285,  285,  285,  285,  295,

      295,  295,  295,  295,  295,  304,  290,  289,  286,  283,
      282,  281,  280,  304,  304,  304,  304,  304,  304,  322,
      279,  278,  277,  276,  274,  273,  322,  322,  322,  322,
      322,  322,  322,  326,  272,  270,  269,  268,  267,  266,
      326,  326,  326,  326,  326,  326,  326,  333,  264,  263,
      262,  258,  257,  256,  255,  333,  333,  333,  333,  333,
      333,  254,  253,  252,  333,  335,  251,  250,  249,  248,
      247,  246,  244,  335,  335,  335,  335,  335,  335,  243,
      242,  238,  335,  356,  237,  236,  235,  234,  233,  232,
      356,  356,  356,  356,  356,  356,  356,  357,  231,  230,

      229,  227,  223,  222,  357,  357,  357,  357,  357,  357,
      357,  361,  221,  361,  220,  361,  361,  361,  361,  361,
      361,  361,  361,  365,  365,  219,  218,  365,  216,  365,
      365,  366,  212,  211,  210,  366,  206,  366,  367,  205,
      367,  198,  196,  189,  367,  183,  367,  368,  163,  162,
      140,  368,  138,  368,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  370,  136,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  371,  135,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      372,  107,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  374,  106,  104,  103,  374,  100,  374,  376,
       89,  376,  377,  377,   56,   52,  377,   48,  377,  378,
       41,  378,   40,  378,   22,  378,  380,   21,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  381,    8,
      381,    3,    0,    0,  381,    0,  381,  383,    0,    0,
        0,  383,    0,  383,  384,    0,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  386,  386,    0,    0,
      386,    0,  386,  388,    0,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  389,    0,    0,    0,  389,
        0,  389,  391,    0,    0,  391,  391,    0,  391,  393,

        0,    0,    0,  393,  393,  393,  395,    0,    0,  395,
      395,    0,  395,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "finalproject.lex"
#define INITIAL 0
#line 2 "finalproject.lex"
    int lineNum = 0;

    void printResultsToFile(char *TextType, char *Text)
    {
        FILE *fptr;
        fptr = fopen("results.txt", "a+");

        fprintf(fptr, "\t%sLine Number: %i\t\t%s\n", TextType, lineNum, Text);
        fclose(fptr);
    }
#line 735 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 61 "finalproject.lex"


#line 889 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1014 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "finalproject.lex"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "finalproject.lex"
{printResultsToFile("Comment\t\t\t\t",yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "finalproject.lex"
{printResultsToFile("Header\t\t\t\t",yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "finalproject.lex"
{printResultsToFile("Namespace\t\t\t",yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "finalproject.lex"
{printResultsToFile("Reserved Word\t\t",yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "finalproject.lex"
{printResultsToFile("Datatype\t\t\t",yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "finalproject.lex"
{printResultsToFile("Brackets\t\t\t",yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "finalproject.lex"
{printResultsToFile("Boolean\t\t\t\t",yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "finalproject.lex"
{printResultsToFile("Float\t\t\t",yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "finalproject.lex"
{printResultsToFile("Integer\t\t\t\t",yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "finalproject.lex"
{printResultsToFile("String\t\t\t\t",yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "finalproject.lex"
{printResultsToFile("Character\t\t\t",yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "finalproject.lex"
{printResultsToFile("Operator\t\t\t",yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "finalproject.lex"
{printResultsToFile("Array\t\t\t\t",yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "finalproject.lex"
{printResultsToFile("Declare Pointer\t\t",yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "finalproject.lex"
{printResultsToFile("Pointer Address\t\t",yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "finalproject.lex"
{printResultsToFile("Pointer\t\t\t\t",yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "finalproject.lex"
{printResultsToFile("Declare Function\t",yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "finalproject.lex"
{printResultsToFile("Function Call\t\t",yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "finalproject.lex"
{printResultsToFile("Structure\t\t\t",yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "finalproject.lex"
{printResultsToFile("Class\t\t\t\t",yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "finalproject.lex"
{printResultsToFile("Template\t\t\t",yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "finalproject.lex"
{printResultsToFile("Friend Class\t\t",yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "finalproject.lex"
{printResultsToFile("Friend Function\t\t",yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "finalproject.lex"
{printResultsToFile("Inheritance\t\t\t",yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "finalproject.lex"
{printResultsToFile("Condition\t\t\t",yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "finalproject.lex"
{printResultsToFile("Variable\t\t\t",yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "finalproject.lex"
{lineNum++;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "finalproject.lex"
ECHO;
	YY_BREAK
#line 1117 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 360);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 93 "finalproject.lex"


int yywrap(){}

int main()
{
    FILE *fptr;
    fptr = fopen("results.txt", "w");
    fclose(fptr);

    FILE *fout;

    fout = fopen("Sample1.cpp","r");
    lineNum=0;
    printResultsToFile("FILE 1\t\t\t\t","Sample1.cpp\n");
    lineNum++;
    yyin = fout;
    yylex();

    fout = fopen("Sample2.cpp","r");
    lineNum=0;
    printResultsToFile("\n\n\tFILE 2\t\t\t\t","Sample2.cpp\n");
    lineNum++;
    yyin=fout;
    yylex();

    fout = fopen("Sample3.cpp","r");
    lineNum=0;
    printResultsToFile("\n\n\tFILE 3\t\t\t\t","Sample3.cpp\n");
    lineNum++;
    yyin=fout;
    yylex();

    //  fout = fopen("Sample4.cpp","r");
    // lineNum=0;
    // printResultsToFile("\n\n\tFILE 4\t\t\t\t","Sample4.cpp\n");
    // lineNum++;
    // yyin=fout;
    // yylex();

    return 0;
}